
POST http://localhost:4000/api/add_comment.php
Content-Type: application/json

{
  "falaise_id": "33",
  "velo_id": "274",
  "commentaire": "test",
  "nom": "test",
  "email": "test",
  "ville_nom": "Lyon",
  "gare_depart": "Part Dieu",
  "gare_arrivee": "Virieu"
}

### Edition
PUT http://localhost:4000/api/edit_comment.php
Content-Type: application/json

{
  "commentaire_id": "2",
  "falaise_id": "33",
  "velo_id": "274",
  "commentaire": "test un peu plus long, j'ai beaucoup aimé l'escalade dans cette falaise. l'accès vélo est top, mais j'ai préféré prendre l'embranchement à droite en sortant du village, c'est à peine plus long, mais on y gagne en tranquilité.\nÀ noter qu'il y a une piste cyclable qui part du centre du village, je n'ai pas testé mais ça me semble aussi une bonne option si on est pas pressé.",
  "nom": "Jean Dupont",
  "email": "jean@dupont.fr",
  "ville_nom": "Lyon",
  "gare_depart": "Part Dieu",
  "gare_arrivee": "Chindrieux"
}
