
###
GET http://localhost:4000/api/private/crons/ingest_cartotrain.php
Authorization: Bearer VG_TOKEN


###
GET https://velogrimpe.fr/api/private/crons/ingest_cartotrain.php
Authorization: Bearer VG_TOKEN

###